"use client";

import { motion, useReducedMotion, useScroll } from "motion/react";
import { useRef } from "react";

import { Rise, useScrub } from "@/components/site/motion-primitives";
import { SectionHead } from "@/components/site/section-head";
import { cn } from "@/lib/utils";

const STAGES = [
  { name: "Detect", by: "Tacit" },
  { name: "Investigate", by: "Investigation · Hunter" },
  { name: "Contain", by: "Defender" },
  { name: "Repair", by: "Recovery" },
  { name: "Recover", by: "Recovery · Coordinator" },
  { name: "Verify", by: "Verification" },
];

const RECONSTRUCTION: { t: string; what: string; detail: string; by: string; threat?: boolean }[] = [
  { t: "00:00.000", what: "Initial entry", detail: "CI token ci-deploy-07 used from an unfamiliar host", by: "Tacit", threat: true },
  { t: "00:00.004", what: "Credential abuse", detail: "Token exchanged for the node-3 service account", by: "Tacit", threat: true },
  { t: "00:00.009", what: "Lateral movement", detail: "node-3 → agent-worker-2, attempted", by: "Forensics", threat: true },
  { t: "00:00.012", what: "Contained", detail: "token.revoke · process.freeze", by: "Tacit" },
  { t: "00:02.140", what: "Isolated", detail: "node.isolate node-3 · checkout rerouted to node-5, node-8", by: "Defender" },
  { t: "01:48.300", what: "Failover", detail: "cloud-a → local-7b, resumed from checkpoint", by: "Gateway" },
  { t: "03:12.406", what: "Rebuilt", detail: "Clean instance deployed · 41 credentials rotated", by: "Recovery" },
  { t: "03:41.090", what: "Final state", detail: "No persistence · no open attack path · services healthy", by: "Verification" },
];

export function Verify() {
  return (
    <section
      id="verify"
      data-surface="bone"
      data-time="T+03:41.090"
      data-stage="Verified"
      aria-labelledby="verify-title"
      className="pb-[clamp(96px,11vw,168px)] scroll-mt-[var(--nav-h)]"
    >
      <div className="frame">
        <SectionHead
          id="verify-title"
          time="T+03:41.090"
          stage="Verified"
          actor="Verification · Forensics"
          title="Closed only when it is shown to be closed."
          lede="Every action enters its own loop of act, observe, verify and replan. If the threat persists or the remedy causes harm, the plan changes. The incident ends in a full reconstruction a person can check."
        />

        <Lifecycle />

        <Rise className="mt-4 border border-plaster">
          <div className="type-mono flex flex-wrap items-center justify-between gap-3 border-b border-plaster px-5 py-4 text-stone sm:px-8">
            <span className="text-soot">Incident reconstruction · INC-2F9C</span>
            <span>Generated by Forensics · resolved</span>
          </div>
          <ol>
            {RECONSTRUCTION.map((r) => (
              <li
                key={r.t}
                className="type-mono grid grid-cols-[5.5rem_1fr] gap-x-4 gap-y-1 border-b border-plaster px-5 py-3.5 last:border-b-0 sm:grid-cols-[6.5rem_10rem_1fr_8rem] sm:px-8"
              >
                <span className="text-stone">{r.t}</span>
                <span className={cn("flex items-center gap-2", r.threat ? "text-rubric" : "text-soot")}>
                  <span className={cn("size-1.5 rounded-full", r.threat ? "bg-rubric" : "bg-soot")} />
                  {r.what}
                </span>
                <span className="col-start-2 text-graphite sm:col-start-auto">{r.detail}</span>
                <span className="col-start-2 text-stone sm:col-start-auto sm:text-right">{r.by}</span>
              </li>
            ))}
          </ol>
        </Rise>
      </div>
    </section>
  );
}

function Lifecycle() {
  const ref = useRef<HTMLDivElement>(null);
  const reduce = useReducedMotion();
  const { scrollYProgress } = useScroll({ target: ref, offset: ["start 0.9", "end 0.5"] });
  const fill = useScrub(scrollYProgress, [0, 1], [0, 1]);

  return (
    <div ref={ref} className="relative mt-[clamp(56px,7vw,104px)] border border-plaster">
      <motion.div
        aria-hidden
        className="absolute inset-x-0 top-0 h-[2px] origin-left bg-soot"
        style={reduce ? undefined : { scaleX: fill }}
      />
      <ol className="grid grid-cols-2 gap-px bg-plaster sm:grid-cols-3 lg:grid-cols-7">
        {STAGES.map((s, i) => (
          <li key={s.name} className="bg-bone px-5 py-6">
            <span className="type-mono text-stone">{String(i + 1).padStart(2, "0")}</span>
            <p className="type-title mt-6 text-soot">{s.name}</p>
            <p className="type-mono mt-2 text-stone">{s.by}</p>
          </li>
        ))}
        <li className="col-span-2 bg-soot px-5 py-6 text-chalk sm:col-span-3 lg:col-span-1">
          <span className="type-mono text-chalk/50">∞</span>
          <p className="type-title mt-6">Continue</p>
          <p className="type-mono mt-2 text-chalk/50">Back to watching</p>
        </li>
      </ol>
    </div>
  );
}
